import { Appointment } from './../classes/appointment';
import { SCHEDULES, PROFESSIONALS } from './../catalogs/schedules';
import * as moment from 'moment';

export const APPOINTMENTS: Appointment[] = [
  {
    schedule: SCHEDULES[1],
    id: 1,
    date: moment(),
    hour: moment().set({ 'hour': 9, 'minute': 30 }).format('HH:mm'),
    patient: 5100,
    professional: PROFESSIONALS[0],
    reminderWay: null,
    reminderData: null,
    indications: 'Indicaciones de prueba',
    reprogrammed: true,
    confirmed: false,
    printed: false,
    reminderSent: false,
  },
  {
    schedule: SCHEDULES[0],
    id: 2,
    date: moment(),
    hour: moment().set({ 'hour': 9, 'minute': 50 }).format('HH:mm'),
    patient: 'Tini',
    professional: PROFESSIONALS[0],
    reminderWay: null,
    reminderData: null,
    indications: 'Indicaciones de prueba',
    reprogrammed: true,
    confirmed: false,
    printed: false,
    reminderSent: false,
  },
  {
    schedule: SCHEDULES[1],
    id: 3,
    date: moment(),
    hour: moment().set({ 'hour': 17, 'minute': 30 }).format('HH:mm'),
    patient: 'Pepe',
    professional: PROFESSIONALS[0],
    reminderWay: null,
    reminderData: null,
    indications: 'Indicaciones de prueba',
    reprogrammed: true,
    confirmed: false,
    printed: false,
    reminderSent: false,
  },
  {
    schedule: SCHEDULES[1],
    id: 1,
    date: moment('20181110'),
    hour: moment().set({ 'hour': 9, 'minute': 50 }).format('HH:mm'),
    patient: 'Lola',
    professional: PROFESSIONALS[0],
    reminderWay: null,
    reminderData: null,
    indications: 'Indicaciones de prueba',
    reprogrammed: true,
    confirmed: false,
    printed: false,
    reminderSent: false,
  },
  {
    schedule: SCHEDULES[0],
    id: 2,
    date: moment('20181110'),
    hour: moment().set({ 'hour': 11, 'minute': 10 }).format('HH:mm'),
    patient: 'Tini',
    professional: PROFESSIONALS[0],
    reminderWay: null,
    reminderData: null,
    indications: 'Indicaciones de prueba',
    reprogrammed: true,
    confirmed: false,
    printed: false,
    reminderSent: false,
  },
  {
    schedule: SCHEDULES[1],
    id: 3,
    date: moment('20181120'),
    hour: moment().set({ 'hour': 11, 'minute': 30 }).format('HH:mm'),
    patient: 'Sonia',
    professional: PROFESSIONALS[0],
    reminderWay: null,
    reminderData: null,
    indications: 'Indicaciones de prueba',
    reprogrammed: true,
    confirmed: false,
    printed: false,
    reminderSent: false,
  },
];
