import { Relative } from './../classes/relative';

export const RELATIVES = [
  { id: 1, name: 'Padre' },
  { id: 2, name: 'Madre' },
  { id: 3, name: 'Abuelo' },
  { id: 4, name: 'Abuela' },
  { id: 5, name: 'Bisabuelo' },
  { id: 6, name: 'Bisabuela' },
  { id: 7, name: 'Hermano' },
  { id: 8, name: 'Hermana' },
  { id: 9, name: 'Sobrino' },
  { id: 10, name: 'Sobrina' },
  { id: 11, name: 'Tío' },
  { id: 12, name: 'Tía' },
  { id: 13, name: 'Primo' },
  { id: 14, name: 'Prima' },
  { id: 15, name: 'Bisnieto' },
  { id: 16, name: 'Bisnieta' },
  { id: 17, name: 'Cónyuge' },
  { id: 18, name: 'Hijo' },
  { id: 19, name: 'Hija' },
  { id: 20, name: 'Nieto' },
  { id: 21, name: 'Nieta' },
  { id: 22, name: 'Yerno' },
  { id: 23, name: 'Nuera' },
  { id: 24, name: 'Suegro' },
  { id: 25, name: 'Suegra' },
  { id: 26, name: 'Abuelo político' },
  { id: 27, name: 'Abuela política' },
  { id: 28, name: 'Cuñado' },
  { id: 29, name: 'Cuñada' },
];
