import { Vaccine } from './../classes/vaccine';

export const VACCINATIONS: Vaccine[] = [
    {id: 1, name: 'BCG', description: 'BCG: Tuberculosis (formas invasivas)'},
    {id: 2, name: 'Hepatitis B', description: 'HB: Hepatitis B'},
    {id: 3, name: 'Neumococo Conjugada', description: 'Previene la Meningitis, Neumonía y Sepsis por Neumococo'},
    // tslint:disable-next-line:max-line-length
    {id: 4, name: 'Quíntuple Pentavalente DTP-HB-Hib', description: 'DTP-HB-Hib: (Pentavalente) Difteria, Tétanos, Tos Convulsa, Hep B, Haemophilus Influenzae b'},
    {id: 5, name: 'Polio - IPV', description: 'IPV: (Salk) Poliovirus inactivada'},
    {id: 6, name: 'Polio - OPV', description: 'OPV: (Sabin) Poliovirus oral'},
    {id: 7, name: 'Rotavirus', description: 'Rotavirus'},
    {id: 8, name: 'Meningococo', description: 'Meningococo'},
    {id: 9, name: 'Gripe', description: 'Antigripal'},
    {id: 10, name: 'Hepatitis A', description: 'HA: Hepatitis A'},
    {id: 11, name: 'Tripe Viral SRP', description: 'SRP: (Triple viral) Sarampión, Rubeóla, Paperas'},
    {id: 12, name: 'Varicela', description: 'Varicela'},
    // tslint:disable-next-line:max-line-length
    {id: 13, name: 'Cuádruple o Quíntuple Pentavalente DTP-Hib', description: 'DTP-Hib: (Cuádruple) Difteria, Tétanos, Tos Convulsa, Haemophilus influenzae b'},
    {id: 14, name: 'Triple Bacteriana Celular DTP', description: 'DTP: (Triple Bacteriana Celular) Difteria, Tétanos, Tos Convulsa'},
    {id: 15, name: 'Triple Bacteriana Acelular dTpa', description: 'dTpa: (Triple Bacteriana Acelular) Difteria, Tétanos, Tos Convulsa'},
    {id: 16, name: 'Virus Papiloma Humano', description: 'VPH: Virus Papiloma Humano'},
    {id: 17, name: 'Doble Bacteriana dT', description: 'dT: (Doble Bacteriana) Difteria, Tétanos'},
    {id: 18, name: 'Doble Viral SR o Triple Viral SRP', description: 'SR: (Doble Viral) Sarampión, Rubeóla'},
    {id: 19, name: 'Fiebre Amarilla', description: 'FA: (Fiebre Amarilla)'},
    {id: 20, name: 'Fiebre Hemorrágica Argentina', description: 'FHA: (Fiebre Hemorrágica Argentina)'},
];

export const AGES = [
    {id: 1, name: 'Recién nacido'},
    {id: 2, name: '2 meses'},
    {id: 3, name: '3 meses'},
    {id: 4, name: '4 meses'},
    {id: 5, name: '5 meses'},
    {id: 6, name: '6 meses'},
    {id: 7, name: '12 meses'},
    {id: 8, name: '15 meses'},
    {id: 9, name: '15-18 meses'},
    {id: 10, name: '18 meses'},
    {id: 11, name: '24 meses'},
    {id: 12, name: '5-6 años (ingreso escolar)'},
    {id: 13, name: '11 años'},
    {id: 14, name: 'A partir de los 15 años'},
    {id: 15, name: 'Adultos'},
    {id: 16, name: 'Embarazadas'},
    {id: 17, name: 'Puerperio'},
    {id: 18, name: 'Personal de salud'},
];

export const DOSES = [
    {id: 1, vaccine: 1, age: 1, name: 'única dosis (A)'},
    {id: 2, vaccine: 2, age: 1, name: 'dosis neonatal (B)'},
    {id: 3, vaccine: 3, age: 2, name: '1° dosis'},
    {id: 4, vaccine: 4, age: 2, name: '1° dosis'},
    {id: 5, vaccine: 5, age: 2, name: '1° dosis'},
    {id: 6, vaccine: 7, age: 2, name: '1° dosis'},
    {id: 7, vaccine: 8, age: 3, name: '1° dosis'},
    {id: 8, vaccine: 3, age: 4, name: '2° dosis'},
    {id: 9, vaccine: 4, age: 4, name: '2° dosis'},
    {id: 10, vaccine: 5, age: 4, name: '2° dosis'},
    {id: 11, vaccine: 7, age: 4, name: '2° dosis (E)'},
    {id: 12, vaccine: 8, age: 5, name: '2° dosis'},
    {id: 13, vaccine: 4, age: 6, name: '3° dosis'},
    {id: 14, vaccine: 6, age: 6, name: '3° dosis'},
    {id: 20, vaccine: 9, age: 6, name: 'dosis anual (F)'},
    {id: 15, vaccine: 3, age: 7, name: 'refuerzo'},
    {id: 21, vaccine: 9, age: 7, name: 'dosis anual (F)'},
    {id: 16, vaccine: 10, age: 7, name: 'única dosis'},
    {id: 18, vaccine: 8, age: 8, name: 'refuerzo'},
    {id: 22, vaccine: 9, age: 8, name: 'dosis anual (F)'},
    {id: 17, vaccine: 11, age: 8, name: '1° dosis'},
    {id: 19, vaccine: 12, age: 8, name: 'única dosis'},
    {id: 26, vaccine: 6, age: 9, name: '1° refuerzo'},
    {id: 23, vaccine: 9, age: 9, name: 'dosis anual (F)'},
    {id: 27, vaccine: 13, age: 9, name: '1° refuerzo'},
    {id: 24, vaccine: 9, age: 10, name: 'dosis anual (F)'},
    {id: 28, vaccine: 19, age: 10, name: '1° dosis (L)'},
    {id: 25, vaccine: 9, age: 11, name: 'dosis anual (F)'},
    {id: 29, vaccine: 6, age: 12, name: '2° refuerzo'},
    {id: 30, vaccine: 11, age: 12, name: '2° dosis'},
    {id: 31, vaccine: 14, age: 12, name: '2° refuerzo'},
    {id: 39, vaccine: 2, age: 13, name: 'iniciar o completar esquema (C)'},
    {id: 32, vaccine: 8, age: 13, name: 'única dosis'},
    {id: 36, vaccine: 11, age: 13, name: 'iniciar o completar esquema (I)'},
    {id: 33, vaccine: 15, age: 13, name: 'refuerzo'},
    {id: 34, vaccine: 16, age: 13, name: '2° dosis (Ñ)'},
    {id: 35, vaccine: 19, age: 13, name: 'refuerzo (M)'},
    {id: 40, vaccine: 2, age: 14, name: 'iniciar o completar esquema (C)'},
    {id: 37, vaccine: 11, age: 14, name: 'iniciar o completar esquema (I)'},
    {id: 45, vaccine: 18, age: 14, name: 'iniciar o completar esquema (I)'},
    {id: 47, vaccine: 20, age: 14, name: 'única dosis (N)'},
    {id: 41, vaccine: 2, age: 15, name: 'iniciar o completar esquema (C)'},
    {id: 38, vaccine: 11, age: 15, name: 'iniciar o completar esquema (I)'},
    {id: 49, vaccine: 17, age: 15, name: 'refuerzo cada 10 años'},
    {id: 46, vaccine: 18, age: 15, name: 'iniciar o completar esquema (I)'},
    {id: 48, vaccine: 20, age: 15, name: 'única dosis (N)'},
    {id: 42, vaccine: 2, age: 16, name: 'iniciar o completar esquema (C)'},
    {id: 50, vaccine: 9, age: 16, name: 'una dosis (G)'},
    {id: 51, vaccine: 15, age: 16, name: 'una dosis (J)'},
    {id: 43, vaccine: 2, age: 17, name: 'iniciar o completar esquema (C)'},
    {id: 52, vaccine: 9, age: 17, name: 'una dosis (H)'},
    {id: 53, vaccine: 11, age: 17, name: 'iniciar o completar esquema (I)'},
    {id: 55, vaccine: 18, age: 17, name: 'iniciar o completar esquema (I)'},
    {id: 44, vaccine: 2, age: 18, name: 'iniciar o completar esquema (C)'},
    {id: 57, vaccine: 9, age: 18, name: 'dosis anual'},
    {id: 54, vaccine: 11, age: 18, name: 'iniciar o completar esquema (I)'},
    {id: 58, vaccine: 15, age: 18, name: 'una dosis (K)'},
    {id: 56, vaccine: 18, age: 18, name: 'iniciar o completar esquema (I)'},
];
